/**
 * Review and patient-film data for the V3 concept page.
 *
 * GENERATED by copying the array literals verbatim out of
 * components/sections/Testimonials/Testimonials.tsx, character for
 * character. It lives here because that file is a Client Component:
 * importing a const from it into a Server Component hands back a client
 * reference rather than the array.
 *
 * Do not hand-edit. If the live reviews change, re-copy them; V3 must
 * render exactly what the homepage renders.
 */

export const REVIEWS = [
  {
    name: 'Dimitrijs Jakovlevs',
    initial: 'D',
    timeAgo: 'Recent',
    categories: ['general', 'minor-surgery', 'laser'],
    review:
      'I visited the clinic for removal of a haemangioma on my forehead. Initially, surgery was discussed due to the size, but during the appointment the doctor decided that laser treatment was the better and less invasive option.\n\nThe procedure itself was quick and straightforward, and I was reassured throughout. After the appointment, I realised there had been some confusion on my side regarding the pricing, as the invoice still reflected surgical treatment. I raised this with the clinic, and the difference was refunded promptly and without any issues.\n\nI really appreciated how professionally and fairly this was handled. Overall, a positive experience — good clinical judgement, clear results, and excellent customer service. I\'d be happy to recommend the clinic.',
  },
  {
    name: 'Daniela Angelova',
    initial: 'D',
    timeAgo: 'Recent',
    categories: ['aesthetics', 'hydrafacial'],
    review:
      'Absolutely loved my HydraFacial triplet! Each session left my skin clearer, brighter, and deeply hydrated. The glow is real and long-lasting. Highly recommend!',
  },
  {
    name: 'Kestutis Astrauskas',
    initial: 'K',
    timeAgo: 'Recent',
    categories: ['general', 'laser-snoring'],
    review:
      'Received good service. Felt welcomed from the beginning, easy communication and booking. Done first anti snoring Laser treatment. So far All ok.',
  },
  {
    name: 'Fran',
    initial: 'F',
    timeAgo: 'Recent',
    categories: ['general'],
    review:
      'Telephoned yesterday as needed urgent advice over issue following facial aesthetic treatment. From first call, to receptionist to nurse and doctor all in one day - super efficient service. Everyone was really kind and helped to settle my anxiety. Big special mention to Dr Virmani who was excellent - cannot thank them enough. Would totally recommend this clinic.',
  },
  {
    name: 'Temesgen Beyen',
    initial: 'T',
    timeAgo: 'Recent',
    categories: ['general'],
    review:
      'Extremely happy Dr Gunjan provided perfect treatment plan.',
  },
  {
    name: 'Sumaiya Hamed',
    initial: 'S',
    timeAgo: 'Recent',
    categories: ['general'],
    review:
      'Amazing Services. They really took their time to explain the different procedures and which option would be best. Would recommend!',
  },
  {
    name: 'Paul',
    initial: 'P',
    timeAgo: 'Recent',
    categories: ['general', 'aesthetics'],
    review:
      'Recently had two procedures undertaken by Mr Sankar at the One Clinic excellent service throughout the process and great follow up care. Would definitely recommend for aesthetic treatments.',
  },
  {
    name: 'Hannah Clauss',
    initial: 'H',
    timeAgo: 'Recent',
    categories: ['general'],
    review:
      'I had a consultation. Firstly they were running 10 minutes behind but kept me informed and offered me a drink etc. With the doctors I was advised my options but ultimately I got to choose what I wanted. Very happy so far.',
  },
  {
    name: 'Rachel',
    initial: 'R',
    timeAgo: 'Recent',
    categories: ['general', 'laser'],
    review:
      'I recently had the new cool laser on my upper and lower eyelids at The One Clinic. I\'m only a week into my treatment and I can already see the results. My eyes look so much fresher and renewed, and my upper lid is definitely tighter and less wrinkled. I can\'t wait to have my lower face done now!!',
  },
  {
    name: 'Shanaz Parvin',
    initial: 'S',
    timeAgo: 'Recent',
    categories: ['general', 'laser'],
    review:
      'Alhamdulillah, I had a very good experience. The staff are well-experienced and treated me exceptionally well. I was suffering from an acne problem, and after the first session, I would say my acne has decreased by 70%. I will be scheduling another session soon.',
  },
  {
    name: 'Jayshree Pancholi',
    initial: 'J',
    timeAgo: 'Recent',
    categories: ['general', 'laser'],
    review:
      'I had scars and pores skin so Dr Gunjan and her team suggested laser treatment. I just had my very first laser treatment and the result I got is amazing. Can\'t believe within one treatment, I will see big difference. My skin tone looks so healthy, bright and smooth, minimised my pores and scars. So happy with my results. I highly recommend laser treatment if you have scars, acne and pores skin. Thank you so much Rosie who did my laser and the whole one clinic team.',
  },
  {
    name: 'Taralyn Cox',
    initial: 'T',
    timeAgo: 'Recent',
    categories: ['general', 'aesthetics'],
    review:
      'Amazing results, informative and caring staff! Definitely worth going to a clinic over a spa setting. I felt heard, cared for and the results speak for themselves. They have a range of options available at different price points and they talk to you about all your options, not just the expensive ones! I had an endolift and Botox and a month after the non-invasive surgery I look great. I can see the difference and it will only get better. Clean facilities, lovely people and a great result. Thanks One Clinic!',
  },
  {
    name: 'Roshni Abi',
    initial: 'R',
    timeAgo: 'Recent',
    categories: ['aesthetics', 'hydrafacial'],
    review:
      'Had my Hydrafacial done today. Loved how relaxing the whole experience was. Everything was very well explained and just cannot get over the glow on my face!',
  },
  {
    name: 'Angelika B',
    initial: 'A',
    timeAgo: 'Recent',
    categories: ['general'],
    review:
      'Thank you for my daughter\'s hydrofacial and further treatment planned. We are hoping that this will help with her acne. Thank you so far.',
  },
  {
    name: 'Mehzabeen Warsi',
    initial: 'M',
    timeAgo: 'Recent',
    categories: ['aesthetics', 'hydrafacial'],
    review:
      'Got my hydrafacial done by Ellie. She explained the process and did a great job. Would definitely recommend. Most importantly very kind and polite. Also met Dr Gunjan who was very informative.',
  },
];

export const PATIENT_VIDEOS = [
  { id: 'idcb1vywka', title: 'Customer Testimonial' },
  { id: 'onscmatqmy', title: 'Customer Testimonial, Oxana' },
  { id: 'fm142sxmlw', title: 'Customer Testimonial, Mahanoor' },
];
